import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "~/components/Navbar";
import Footer from "~/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Code Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex h-screen  w-full flex-col justify-between">
          <div className="sticky top-0 z-50">
            <Navbar />
          </div>
          <div className="flex items-center justify-center px-5 lg:px-10">
            {children}
          </div>
          <div className="fixed bottom-0 w-full">
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
